swagger: '2.0'

info:
  version: '0.0.1'
  title: 'auto-release API'
  description: 'auto-release API规范'
  
host: localhost # NOTE: change to your own host.

schemes:
  - http
  
basePath: /

produces:
  - application/json
  
paths:
  /projects:
    get:
      description: '获得该服务器上所有的项目'
      responses:
        200:
          description: '正常返回'
          schema:
            type: array
            summary: 项目列表
            items:
              $ref: Project
      tags: []
    

definitions:
  Project:
    properties:
      id:
        type: integer
        format: int32
        description: 项目ID
      name:
        type: string
        description: 项目名称
      description:
        type: string
        description: 项目简介
      website:
        type: string
        format: url
        description: 项目网站
      license:
        type: string
        description: 项目使用的协议
      